// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7x6w-tR5U9SJzshN9X2Hh8z1T2yqu1mk',
    appId: '1:127595726955:web:112eb9b4567db81960c92e',
    messagingSenderId: '127595726955',
    projectId: 'daily-price-list',
    authDomain: 'daily-price-list.firebaseapp.com',
    storageBucket: 'daily-price-list.firebasestorage.app',
    measurementId: 'G-LQDK1KBQF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwSgEj2VPReLsLQo0qRjKgViorMX4Nw0A',
    appId: '1:127595726955:android:bb656eb86d99cb3860c92e',
    messagingSenderId: '127595726955',
    projectId: 'daily-price-list',
    storageBucket: 'daily-price-list.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx3dwPhyCG3dFpGIBG0JxhGgHR_UStwZY',
    appId: '1:127595726955:ios:6893240b984cbf4460c92e',
    messagingSenderId: '127595726955',
    projectId: 'daily-price-list',
    storageBucket: 'daily-price-list.firebasestorage.app',
    iosBundleId: 'com.example.dailyPriceList',
  );
}
